version: "3.9"

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN
      - TELEGRAM_CHANNEL_ID
      - DATABASE_URL
      - SOURCES_CONFIG_PATH=/app/sources.yaml
      - CAPTION_TEMPLATE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - LOG_LEVEL
    restart: always
    volumes:
      - ./sources.yaml:/app/sources.yaml:ro
      - ./gdrive_credentials:/app/gdrive_credentials:ro
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
