name: Deploy to Production Server (Secure, No .env file)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Переменные для SSH-подключения и путей
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Create creds directory (if needed for rsync)
        run: mkdir -p gdrive_credentials

      - name: Write Google Drive credentials from Secrets
        run: |
          echo "${{ secrets.GDRIVE_JOHN_JSON }}" > gdrive_credentials/john.json
          echo "${{ secrets.GDRIVE_JANE_JSON }}" > gdrive_credentials/jane.json
          # ...Повторить для каждого источника

      - name: Ensure deploy path exists & set ownership
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} \
            "mkdir -p ${{ env.DEPLOY_PATH }} && chown ${{ env.SERVER_USER }}:${{ env.SERVER_USER }} ${{ env.DEPLOY_PATH }}"

      - name: Sync project to server via rsync
        run: |
          rsync -az --info=progress2 --delete \
            --exclude '.git*' --exclude 'app/tests/' --exclude '.github/' \
            -e "ssh -o StrictHostKeyChecking=no" ./ \
            ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.DEPLOY_PATH }}/

      - name: Deploy and Restart Services via stdin pipe
        id: deploy_step
        # Эта секция передает секреты через stdin напрямую в docker-compose
        run: |
          (
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}"
            echo "TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}"
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
          ) | ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'bash -s' << 'EOF'
            # Включить подробный вывод команд и остановку при ошибке.
            # Это безопасно, так как секреты не являются частью команд.
            set -ex

            # Перейти в директорию проекта
            cd ${{ env.DEPLOY_PATH }}

            echo "### 1. Pulling latest images... ###"
            docker compose pull

            echo "### 2. Stopping and removing old containers... ###"
            docker compose down --remove-orphans

            echo "### 3. Starting new containers with secrets from stdin... ###"
            # Ключевая команда: --env-file - читает переменные из stdin (из пайплайна)
            docker compose --env-file - up -d

            echo "### 4. Deployment successful! Showing running containers: ###"
            docker compose ps
          EOF

      - name: Show Docker logs on failure
        # Этот шаг выполняется, только если предыдущий шаг ('deploy_step') завершился с ошибкой
        if: failure()
        run: |
          echo "🔴 Deployment failed. Fetching application logs from server..."
          ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "
            cd ${{ env.DEPLOY_PATH }}
            echo '--- Docker container statuses (docker compose ps -a) ---'
            docker compose ps -a
            echo '--- Last 50 lines of logs from each container (docker compose logs) ---'
            docker compose logs --tail=50
          "
